name: asi
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  datetime_picker_formfield: ^2.0.0
  dotted_border: ^2.0.0+1
  extended_image: ^4.2.1
  image_editor: ^1.0.0
  image_picker: ^0.8.4
  flutter_spinkit: ^5.1.0
  flutter_secure_storage: ^4.2.1
  dio: ^4.0.0
  shared_preferences: ^2.0.8
  mdi: ^5.0.0-nullsafety.0
  flutter_typeahead: ^3.2.1
  package_info_plus: ^1.3.0
  get_storage: ^2.0.3
  flutter_multi_formatter: ^2.4.1
  flutter_svg: ^0.23.0+1
  collection: ^1.15.0
  cached_network_image: ^3.1.0+1
  photo_view: ^0.13.0
  background_fetch: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/isotipo.png
    - assets/images/login_bg.png
    - assets/images/embarque.png
    - assets/images/inspeccion.png
    - assets/images/no-ots.png
    - assets/images/half_progress.svg
    - assets/images/complete_progress.svg
  fonts:
    - family: ASiIcons
      fonts:
        - asset: assets/fonts/ASiIcons.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
